language: csharp
mono: none
dotnet: 2.1.500
os:
- osx
- linux
- windows
env:
  matrix:
  - TestBuildPropsDirectly=true
  - TestBuildPropsDirectly=false
branches:
  only:
  - master
script:
- dotnet build -c Release
- dotnet test -c Release
