version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - TestBuildPropsDirectly: true
    
    - TestBuildPropsDirectly: false
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
